name: C project Arthur

on:
  push:
    branches:
      - dev
      - master

jobs:

  Build:
    runs-on: ubuntu-latest
    name: Building

    steps:
      - name: install nasm
        run: |
          sudo apt install nasm
      - name: Compile project
        run: |
          ls
          make
      - name: Full clean project
        run: |
          make fclean
      - name: Full clean and compile project
        run: |
          make re
      - name: Clean project
        run: |
          make clean

  Unit-test:
    needs: build
    runs-on: ubuntu-18.04
    name: Testing

    steps:
      - name: Install criterion and gcovr
        run: |
          sudo add-apt-repository ppa:snaipewastaken/ppa
          sudo apt update
          sudo apt install criterion-dev gcovr
          sudo apt install nasm
      - uses: actions/checkout@v2
      - name: Compile and launch tests
        run: |
          make tests_run

  # # push-epitech:
  # #   needs: build
  # #   runs-on: ubuntu-latest
  # #   steps:
  # #     - uses: actions/checkout@v2
  # #     - name: fetch all commits
  # #       run: git fetch --prune --unshallow
  # #     - name: setup ssh
  # #       run: |
  # #         mkdir -p ~/.ssh
  # #         eval `ssh-agent`
  # #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  # #         chmod 400 ~/.ssh/id_rsa
  # #         ssh-add
  # #         ssh-keyscan git.epitech.eu > ~/.ssh/known_hosts
  # #     - name: add repository
  # #       run: git remote add epitech ##git@git.epitech.eu:/philippe.loctaux@epitech.eu/test_workshop
  # #     - name: push to repository
  # #       run: git push epitech master
